/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ea3476182f82d390e77c9df
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { DriverService } from '../../services/driver.service';
// Import Models
import { Driver } from '../../domain/car-hexa_db/driver';

// START - USED SERVICES
/**
* DriverService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* DriverService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Driver
 * @class DriverListComponent
 */
@Component({
    selector: 'app-driver-list',
    templateUrl: './driver-list.component.html',
    styleUrls: ['./driver-list.component.css']
})
export class DriverListComponent implements OnInit {
    list: Driver[];
    search: any = {};
    idSelected: string;
    constructor(
        private driverService: DriverService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.driverService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Driver to remove
     *
     * @param {string} id Id of the Driver to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Driver
     */
    deleteItem() {
        this.driverService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
