/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ea3476182f82d390e77c9df
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE driverBaseService PLEASE EDIT ../driver.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Driver } from '../../domain/car-hexa_db/driver';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Driver.service.ts
 */

/*
 * SCHEMA DB Driver
 *
	{
		Address: {
			type: 'String',
			required : true
		},
		FirstName: {
			type: 'String',
			required : true
		},
		LastName: {
			type: 'String',
			required : true
		},
		License: {
			type: 'String',
			required : true
		},
		phone: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Driver: {
			type: Schema.ObjectId,
			ref : "User"
		},
		_passengerObject: {
			type: Schema.ObjectId,
			ref : "Driver"
		},
	}
 *
 */
@Injectable()
export class DriverBaseService {

    contextUrl: string = environment.endpoint + '/driver';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * DriverService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Driver): Observable<Driver> {
        return this.http
            .post<Driver>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * DriverService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DriverService.findBy_passengerObject
    *   @description CRUD ACTION findBy_passengerObject
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_passengerObject(id: string): Observable<Driver[]> {
        return this.http
            .get<Driver[]>(this.contextUrl + '/findBy_passengerObject/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * DriverService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Driver> {
        return this.http
            .get<Driver>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DriverService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Driver[]> {
        return this.http
            .get<Driver[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * DriverService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Driver): Observable<Driver> {
        return this.http
            .post<Driver>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
