/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ea3476182f82d390e77c9df
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { PassengerObjectService } from '../../services/passenger-object.service';
import { DriverService } from '../../services/driver.service';
// Import Models
import { PassengerObject } from '../../domain/car-hexa_db/passenger-object';
import { Driver } from '../../domain/car-hexa_db/driver';

// START - USED SERVICES
/**
* PassengerObjectService.create
*	@description CRUD ACTION create
*
* PassengerObjectService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* PassengerObjectService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* DriverService.findBy_passengerObject
*	@description CRUD ACTION findBy_passengerObject
*	@param Objectid key Id of model to search for
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a PassengerObject
 */
@Component({
    selector: 'app-passenger-object-edit',
    templateUrl: 'passenger-object-edit.component.html',
    styleUrls: ['passenger-object-edit.component.css']
})
export class PassengerObjectEditComponent implements OnInit {
    item: PassengerObject;
    externalDriver__passengerObject: Driver[];
    model: PassengerObject;
    formValid: Boolean;

    constructor(
    private passengerobjectService: PassengerObjectService,
    private driverService: DriverService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new PassengerObject();
        this.externalDriver__passengerObject = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.passengerobjectService.get(id).subscribe(item => this.item = item);
                this.driverService.findBy_passengerObject(id).subscribe(list => this.externalDriver__passengerObject = list);
            }
            // Get relations
        });
    }


    /**
     * Save PassengerObject
     *
     * @param {boolean} formValid Form validity check
     * @param PassengerObject item PassengerObject to save
     */
    save(formValid: boolean, item: PassengerObject): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.passengerobjectService.update(item).subscribe(data => this.goBack());
            } else {
                this.passengerobjectService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



